### ISSUE TITLE
The misc tutorial refers to saved PNGs Atom feed

### ISSUE THREAD

**Issue by fih12616** [ocsigen/ocsigen.org-data#12]
Delete ", and the owner will have the ability to save the drawing they
want and create an Atom feed containing all saved drawings" in file:
https://github.com/ocsigen/ocsigen.org-data/blob/master/tuto/dev/manual/src/misc.wiki

(in all current versions since 5)

This feature relies on the Atom feed module for eliom that has been removed in version 5.0, the implementation has been removed in the tutorial, only this line remains.

OR:
Explain how to use the "syndic" and "river" libraries to do this!

**Comment by vasilisp** [comment]
Thanks!
